######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 18 15:57:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += xml
