include $(S)/build/Makefile.top

LUA_NAME := $(shell for lua in lua lua5.1 ; do if pkg-config $$lua ; then echo $$lua ; break ; fi ; done)

# List of all makefiles in direct subdirectories. If a new subdirectory is
# made, it goes here.
include $(S)/3rd_party/Makefile.dir
include $(S)/src/Makefile.dir
include $(S)/tests/Makefile.dir
# This one for documentation for the build system
include $(S)/build/Makefile.dir

include $(S)/build/Makefile.bottom
