#!/bin/sh

set -e

export PATH=./tests:"$PATH"

for case in tests/full/cases/* ; do
	echo "===================================================================="
	echo "Running test: $case"
	echo "===================================================================="
	./tests/full-test "$case"
done

echo "Test end"

