BINARIES += tests/test_runner

test_runner_MODULES := runner

test_runner_PKG_CONFIGS := $(LUA_NAME) libnetconf
test_runner_EXE_CONFIGS := xslt xml2
test_runner_LOCAL_LIBS := nuci_core
test_runner_SYSTEM_LIBS := uci
