#!/bin/sh

export PATH=./tests:"$PATH"

socat STDIO EXEC:'./bin/nuci -e trace -s disable',pty <<ENDXML
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]><?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="An id">
  <set xmlns='http://www.nic.cz/ns/router/time'>
    <time>2013-10-07T16:26:43+0200</time>
    <utc/>
  </set>
</rpc>
]]>]]>
ENDXML
