#!/bin/sh

socat STDIO EXEC:'./bin/nuci -e trace -s disable',pty <<ENDXML
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]><?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-config>
    <source><running/></source>
    <filter type='subtree'><updater-config xmlns='http://www.nic.cz/ns/router/updater'/></filter>
  </get-config>
</rpc>
]]>]]><?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns='urn:ietf:params:xml:ns:netconf:base:1.0' message-id='2'>
<edit-config>
  <target>
    <running/>
  </target>
  <config>
    <updater-config xmlns="http://www.nic.cz/ns/router/updater">
      <active-lists>
        <user-list xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="delete">
          <name>nas</name>
        </user-list>
      </active-lists>
    </updater-config>
  </config>
</edit-config>
</rpc>
]]>]]>
ENDXML
