#!/bin/sh

cat <<ENDXML | socat STDIO EXEC:./bin/nuci,pty
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]><?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <data xmlns="http://www.nic.cz/ns/router/config">
        <bla>42</bla>
      </data>
    </config>
  </edit-config>
</rpc>
]]>]]>
ENDXML
