######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 12 15:40:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
SOURCES += main.cpp config.cpp cmodel.cpp
HEADERS += config.h cmodel.h
FORMS += config.ui
