NUCI_PLUGINS := \
	stats \
	uci-raw \
	nethist \
	supervisor_test \
	registration \
	updater \
	time
LUA_PLUGINS += $(addprefix src/lua_plugins/, $(NUCI_PLUGINS))

NUCI_PLUGINS_BARE := \
	ap_testing1 \
	init
LUA_PLUGINS_BARE += $(addprefix src/lua_plugins/, $(NUCI_PLUGINS_BARE))
