HELPERS := config-restore config-backup checkconn
SCRIPTS += $(addprefix src/helpers/nuci-helper-,$(HELPERS))

define HELPER_VAR
nuci-helper-$(1)_SOURCE := $(1).sh

endef

$(eval $(foreach HELPER,$(HELPERS),$(call HELPER_VAR,$(HELPER))))
