NUCI_LIBRARIES := \
	datastore \
	editconfig \
	nutils \
	commits \
	views \
	xmltree \
	stacktraceplus \
	tableutils \
	views_supervisor \
	abstraction_plugin
LUA += $(addprefix src/lua_lib/, $(NUCI_LIBRARIES))
