#include <stdio.h>
#include <stdlib.h>

#include "communication.h"

//LIBs
#include <libnetconf.h>


static const char *DATASTORE_MODEL_PATH = SOURCE_DIRECTORY "/src/datastore.yin";

void callback_print(NC_VERB_LEVEL level, const char *msg) {
	const char *level_message = "<UNKNOWN>";
	switch (level) {
		case NC_VERB_ERROR:
			level_message = "ERROR";
			break;
		case NC_VERB_WARNING:
			level_message = "WARNING";
			break;
		case NC_VERB_VERBOSE:
			level_message = "VERBOSE";
			break;
		case NC_VERB_DEBUG:
			level_message = "DEBUG";
			break;
	}
	fprintf(stderr, "%s\t%s\n", level_message, msg);
}

int main(int argc, const char *argv[]) {
	(void) argc;
	(void) argv;
	struct srv_config config;
	bool init;

	//some setting
	//Set verbosity and function to print libnetconf's messages
	nc_verbosity(NC_VERB_DEBUG);
	nc_callback_print(callback_print);

	init = comm_init(DATASTORE_MODEL_PATH, &config);
	// FIXME: ? So, is true success or failure? Should we abort on failure?
	if (!init) {
		//error message was generated by callback_print
		fprintf(stderr, "Nothing to do here\n");
		return 1;
	}

	comm_start_loop(&config);
	comm_cleanup(&config);

	return 0;
}
