#include "communication.h"
#include "interpreter.h"
#include "register.h"
#include "logging.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <libnetconf.h>
#include <libxml/parser.h>

static enum log_level levels[] = {
	[NC_VERB_ERROR] = NLOG_ERROR,
	[NC_VERB_WARNING] = NLOG_WARN,
	[NC_VERB_VERBOSE] = NLOG_DEBUG,
	[NC_VERB_DEBUG] = NLOG_TRACE
};

static void callback_print(NC_VERB_LEVEL level, const char *msg) {
	nlog(levels[level], "%s", msg);
}

int main(int argc, const char *argv[]) {
	(void) argc;
	(void) argv;

	//some setting
	//Set verbosity and function to print libnetconf's messages
	nc_verbosity(NC_VERB_DEBUG);
	nc_callback_print(callback_print);

	//Initialize libxml2 library
	xmlInitParser();
		LIBXML_TEST_VERSION

	struct interpreter *interpreter = interpreter_create();
	if (!interpreter_load_plugins(interpreter, PLUGIN_PATH "/lua_plugins"))
		return 1;

	bool init = comm_init(&global_srv_config, interpreter);

	if (!init) {
		//error message was generated by callback_print
		return 1;
	}

	comm_start_loop(&global_srv_config);
	comm_cleanup(&global_srv_config);

	interpreter_destroy(interpreter);

	//Clean up phase of libxml2
	xmlCleanupParser();
	xmlMemoryDump();

	return 0;
}
