#include <stdio.h>
#include <stdlib.h>

#include "communication.h"

//LIBs
#include <libnetconf.h>


static const char *DATASTORE_MODEL_PATH = SOURCE_DIRECTORY "/src/datastore.yin";
static const char *DATASTORE_FILE_PATH = OUTPUT_DIRECTORY "/src/datastore.xml";

void callback_print(NC_VERB_LEVEL level, const char *msg) {
	fprintf(stderr, "Message:\n %s\n", msg);
}

int main(int argc, char **argv) {
	struct srv_config config;
	int init_result;
	
	//some setting
	//Set verbosity and function to print libnetconf's messages
	nc_verbosity(NC_VERB_DEBUG);
	nc_callback_print(callback_print);
	
	init_result = comm_init(DATASTORE_MODEL_PATH, DATASTORE_FILE_PATH, &config);
	if (init_result == 0) {
		//error message was generated by callback_print
		fprintf(stderr, "Nothing to do here\n"); 
	}
	
	comm_start_loop(config);
	comm_cleanup(config);

	
	return 0;
}
