BINARIES += src/nuci

nuci_MODULES := main \
	communication \
	nuci_datastore \
	interpreter \
	register \
	model

nuci_PKG_CONFIGS := $(LUA_NAME) libnetconf
nuci_EXE_CONFIGS := xml2
nuci_LOCAL_LIBS := xmlwrap
nuci_SYSTEM_LIBS := uci

DOCS += src/plugins

include $(S)/src/xmlwrap/Makefile.dir
